# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_access.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data_access.proto',
  package='com.cit.data.grcp',
  syntax='proto3',
  serialized_options=b'P\001',
  serialized_pb=b'\n\x11\x64\x61ta_access.proto\x12\x11\x63om.cit.data.grcp\"\x1c\n\x0cTweetRequest\x12\x0c\n\x04\x66lag\x18\x01 \x01(\x08\"F\n\rTweetResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x0c\n\x04user\x18\x03 \x01(\t\x12\r\n\x05tweet\x18\x04 \x01(\t2^\n\x0cTweetService\x12N\n\x07request\x12\x1f.com.cit.data.grcp.TweetRequest\x1a .com.cit.data.grcp.TweetResponse0\x01\x42\x02P\x01\x62\x06proto3'
)




_TWEETREQUEST = _descriptor.Descriptor(
  name='TweetRequest',
  full_name='com.cit.data.grcp.TweetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flag', full_name='com.cit.data.grcp.TweetRequest.flag', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=68,
)


_TWEETRESPONSE = _descriptor.Descriptor(
  name='TweetResponse',
  full_name='com.cit.data.grcp.TweetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.cit.data.grcp.TweetResponse.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='com.cit.data.grcp.TweetResponse.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='com.cit.data.grcp.TweetResponse.user', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tweet', full_name='com.cit.data.grcp.TweetResponse.tweet', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=140,
)

DESCRIPTOR.message_types_by_name['TweetRequest'] = _TWEETREQUEST
DESCRIPTOR.message_types_by_name['TweetResponse'] = _TWEETRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TweetRequest = _reflection.GeneratedProtocolMessageType('TweetRequest', (_message.Message,), {
  'DESCRIPTOR' : _TWEETREQUEST,
  '__module__' : 'data_access_pb2'
  # @@protoc_insertion_point(class_scope:com.cit.data.grcp.TweetRequest)
  })
_sym_db.RegisterMessage(TweetRequest)

TweetResponse = _reflection.GeneratedProtocolMessageType('TweetResponse', (_message.Message,), {
  'DESCRIPTOR' : _TWEETRESPONSE,
  '__module__' : 'data_access_pb2'
  # @@protoc_insertion_point(class_scope:com.cit.data.grcp.TweetResponse)
  })
_sym_db.RegisterMessage(TweetResponse)


DESCRIPTOR._options = None

_TWEETSERVICE = _descriptor.ServiceDescriptor(
  name='TweetService',
  full_name='com.cit.data.grcp.TweetService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=142,
  serialized_end=236,
  methods=[
  _descriptor.MethodDescriptor(
    name='request',
    full_name='com.cit.data.grcp.TweetService.request',
    index=0,
    containing_service=None,
    input_type=_TWEETREQUEST,
    output_type=_TWEETRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TWEETSERVICE)

DESCRIPTOR.services_by_name['TweetService'] = _TWEETSERVICE

# @@protoc_insertion_point(module_scope)
