# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import data_access_pb2 as data__access__pb2


class TweetServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.request = channel.unary_stream(
        '/com.cit.data.grcp.TweetService/request',
        request_serializer=data__access__pb2.TweetRequest.SerializeToString,
        response_deserializer=data__access__pb2.TweetResponse.FromString,
        )


class TweetServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def request(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TweetServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'request': grpc.unary_stream_rpc_method_handler(
          servicer.request,
          request_deserializer=data__access__pb2.TweetRequest.FromString,
          response_serializer=data__access__pb2.TweetResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.cit.data.grcp.TweetService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
