# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import processing_pb2 as processing__pb2


class ProcessingStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.process = channel.unary_unary(
        '/ie.cit.grpc.Processing/process',
        request_serializer=processing__pb2.PrRequest.SerializeToString,
        response_deserializer=processing__pb2.PrResponse.FromString,
        )


class ProcessingServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def process(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProcessingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'process': grpc.unary_unary_rpc_method_handler(
          servicer.process,
          request_deserializer=processing__pb2.PrRequest.FromString,
          response_serializer=processing__pb2.PrResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ie.cit.grpc.Processing', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
