# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: processing.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='processing.proto',
  package='ie.cit.grpc',
  syntax='proto3',
  serialized_options=b'P\001',
  serialized_pb=b'\n\x10processing.proto\x12\x0bie.cit.grpc\"\x1a\n\tPrRequest\x12\r\n\x05tweet\x18\x01 \x01(\t\"6\n\nPrResponse\x12\x14\n\x0csymbol_count\x18\x01 \x01(\x03\x12\x12\n\nword_count\x18\x02 \x01(\x03\x32H\n\nProcessing\x12:\n\x07process\x12\x16.ie.cit.grpc.PrRequest\x1a\x17.ie.cit.grpc.PrResponseB\x02P\x01\x62\x06proto3'
)




_PRREQUEST = _descriptor.Descriptor(
  name='PrRequest',
  full_name='ie.cit.grpc.PrRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tweet', full_name='ie.cit.grpc.PrRequest.tweet', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=59,
)


_PRRESPONSE = _descriptor.Descriptor(
  name='PrResponse',
  full_name='ie.cit.grpc.PrResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol_count', full_name='ie.cit.grpc.PrResponse.symbol_count', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='word_count', full_name='ie.cit.grpc.PrResponse.word_count', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['PrRequest'] = _PRREQUEST
DESCRIPTOR.message_types_by_name['PrResponse'] = _PRRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PrRequest = _reflection.GeneratedProtocolMessageType('PrRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRREQUEST,
  '__module__' : 'processing_pb2'
  # @@protoc_insertion_point(class_scope:ie.cit.grpc.PrRequest)
  })
_sym_db.RegisterMessage(PrRequest)

PrResponse = _reflection.GeneratedProtocolMessageType('PrResponse', (_message.Message,), {
  'DESCRIPTOR' : _PRRESPONSE,
  '__module__' : 'processing_pb2'
  # @@protoc_insertion_point(class_scope:ie.cit.grpc.PrResponse)
  })
_sym_db.RegisterMessage(PrResponse)


DESCRIPTOR._options = None

_PROCESSING = _descriptor.ServiceDescriptor(
  name='Processing',
  full_name='ie.cit.grpc.Processing',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=117,
  serialized_end=189,
  methods=[
  _descriptor.MethodDescriptor(
    name='process',
    full_name='ie.cit.grpc.Processing.process',
    index=0,
    containing_service=None,
    input_type=_PRREQUEST,
    output_type=_PRRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROCESSING)

DESCRIPTOR.services_by_name['Processing'] = _PROCESSING

# @@protoc_insertion_point(module_scope)
